name: CI/CD Express API (Self-hosted)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t express-api-image:latest .

      - name: Run Docker Container
        run: |
          docker stop express-api-container || true
          
          docker rm express-api-container || true
          
          docker run -d \
            --name express-api-container \
            -p 3000:3000 \
            --restart always \
            express-api-image:latest

      - name: Cleanup old images
        run: |
          docker image prune -f